// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4tGcNFfI5iizJlKHtit7v8bzT8XRdCI8',
    appId: '1:483392198456:web:9536950c10ceaa58c1d3cd',
    messagingSenderId: '483392198456',
    projectId: 'fingerprint-attendence-34b3d',
    authDomain: 'fingerprint-attendence-34b3d.firebaseapp.com',
    storageBucket: 'fingerprint-attendence-34b3d.firebasestorage.app',
    measurementId: 'G-XDXXRTZSQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1feQ7d0dz0Eu6vNfWb9--Xj_BIilp9bs',
    appId: '1:483392198456:android:3625652ac19e9413c1d3cd',
    messagingSenderId: '483392198456',
    projectId: 'fingerprint-attendence-34b3d',
    storageBucket: 'fingerprint-attendence-34b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7COKNsaEwohkgFo5wzUF9wcs6jXmXCCk',
    appId: '1:483392198456:ios:a1961783110f371fc1d3cd',
    messagingSenderId: '483392198456',
    projectId: 'fingerprint-attendence-34b3d',
    storageBucket: 'fingerprint-attendence-34b3d.firebasestorage.app',
    iosBundleId: 'com.example.fingerprintAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7COKNsaEwohkgFo5wzUF9wcs6jXmXCCk',
    appId: '1:483392198456:ios:a1961783110f371fc1d3cd',
    messagingSenderId: '483392198456',
    projectId: 'fingerprint-attendence-34b3d',
    storageBucket: 'fingerprint-attendence-34b3d.firebasestorage.app',
    iosBundleId: 'com.example.fingerprintAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4tGcNFfI5iizJlKHtit7v8bzT8XRdCI8',
    appId: '1:483392198456:web:39a32d284a603324c1d3cd',
    messagingSenderId: '483392198456',
    projectId: 'fingerprint-attendence-34b3d',
    authDomain: 'fingerprint-attendence-34b3d.firebaseapp.com',
    storageBucket: 'fingerprint-attendence-34b3d.firebasestorage.app',
    measurementId: 'G-NLVKGZB5DW',
  );
}
